#!/bin/bash

SCENARIOS="symfony2 symfony3 symfony4 dev4"

AUTOLOAD_DIRECTORIES='src tests'

stability_dev4='dev'

platform_php_symfony2='5.5'
platform_php_symfony3='5.6'

requirement_symfony2='symfony/console:^2.8'
requirement_symfony3='symfony/console:^3'
requirement_symfony4='symfony/console:^4'
requirement_dev4='symfony/console:^4'
